# Bluesky configuration
# Replace with your actual Bluesky handle
handle: defreyssinet.social
max_posts: 3

# Optional: Filter settings
filter_reposts: true  # Don't include reposts, only original posts
filter_replies: true  # Don't include replies, only top-level posts
